"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.threejs = exports.StateHolder = exports.MaterialUI = exports.Hooks = void 0;
exports.Hooks = require("./Hooks");
exports.MaterialUI = require("./Material-UI");
var StateHolder_1 = require("./StateHolder");
Object.defineProperty(exports, "StateHolder", { enumerable: true, get: function () { return StateHolder_1.StateHolder; } });
const Debug_1 = require("./three.js/Debug");
const THREEView_1 = require("./three.js/THREEView");
const useWebGLRenderer_1 = require("./three.js/useWebGLRenderer");
const Utility_1 = require("./three.js/Utility");
var threejs;
(function (threejs) {
    threejs.createAxisGeometry = Debug_1.createAxisGeometry;
    threejs.createBounds2DGeometry = Debug_1.createBounds2DGeometry;
    threejs.THREEView = THREEView_1.THREEView;
    threejs.SizePropertiesDefault = THREEView_1.SizePropertiesDefault;
    threejs.useWebGLRenderer = useWebGLRenderer_1.useWebGLRenderer;
    threejs.physicalToWindowPixelRatio = Utility_1.physicalToWindowPixelRatio;
    threejs.createZeroCenteredBox = Utility_1.createZeroCenteredBox;
    threejs.createOrthographicCamera = Utility_1.createOrthographicCamera;
    threejs.createWebGLRenderer = Utility_1.createWebGLRenderer;
    threejs.clearScene = Utility_1.clearScene;
    threejs.calculateRenderSize = Utility_1.calculateRenderSize;
    threejs.createViewPortBox = Utility_1.createViewPortBox;
})(threejs = exports.threejs || (exports.threejs = {}));
